### ISSUE TITLE
@stylable/optimizer@2.3.1: Cannot read property 'isEmpty' of undefined

### ISSUE THREAD

**Issue by dangreen** [wix/stylable#859]
```
/Users/dangreen/github/DevFest-Siberia/node_modules/csso/lib/clean/Rule.js:83
    if (node.prelude.children.isEmpty() ||
                              ^

TypeError: Cannot read property 'isEmpty' of undefined
    at Object.cleanRuleset (/Users/dangreen/github/DevFest-Siberia/node_modules/csso/lib/clean/Rule.js:83:31)
    at Object.leave (/Users/dangreen/github/DevFest-Siberia/node_modules/csso/lib/clean/index.js:16:37)
    at List.walkNode (/Users/dangreen/github/DevFest-Siberia/node_modules/csso/node_modules/css-tree/lib/walker/create.js:161:19)
    at List.each (/Users/dangreen/github/DevFest-Siberia/node_modules/csso/node_modules/css-tree/lib/utils/list.js:159:12)
    at Object.eval [as StyleSheet] (eval at createTypeIterator (/Users/dangreen/github/DevFest-Siberia/node_modules/csso/node_modules/css-tree/lib/walker/create.js:112:12), <anonymous>:5:15)
    at walkNode (/Users/dangreen/github/DevFest-Siberia/node_modules/csso/node_modules/css-tree/lib/walker/create.js:158:37)
    at walk (/Users/dangreen/github/DevFest-Siberia/node_modules/csso/node_modules/css-tree/lib/walker/create.js:214:9)
    at module.exports (/Users/dangreen/github/DevFest-Siberia/node_modules/csso/lib/clean/index.js:13:5)
    at compressChunk (/Users/dangreen/github/DevFest-Siberia/node_modules/csso/lib/compress.js:68:5)
    at compress (/Users/dangreen/github/DevFest-Siberia/node_modules/csso/lib/compress.js:153:9)
    at minify (/Users/dangreen/github/DevFest-Siberia/node_modules/csso/lib/index.js:94:9)
    at Object.minifyStylesheet [as minify] (/Users/dangreen/github/DevFest-Siberia/node_modules/csso/lib/index.js:123:12)
    at StylableOptimizer.minifyCSS (/Users/dangreen/github/DevFest-Siberia/node_modules/@stylable/optimizer/src/stylable-optimizer.ts:29:21)
    at StylableGenerator.getCSSInJSWithAssets (/Users/dangreen/github/DevFest-Siberia/node_modules/@stylable/webpack-plugin/src/stylable-generator.ts:161:49)
    at StylableGenerator.toCSS (/Users/dangreen/github/DevFest-Siberia/node_modules/@stylable/webpack-plugin/src/stylable-generator.ts:82:21)
    at modulesByDepth.map.module (/Users/dangreen/github/DevFest-Siberia/node_modules/@stylable/webpack-plugin/src/stylable-module-helpers.ts:177:42)
```

with v2.1.1 all works

**Comment by tomrav** [comment]
Between the two versions in question, we transitioned from using `clean-css` to using `csso` as our minifier for CSS, which resolved a couple of existing bugs. This is the first bug we're encountering with `csso`.

Do you have any idea what input is triggering the error?

**Comment by dangreen** [comment]
@tomrav 

```css
:global([tabindex=-1]:focus) {
	outline: 0 !important;
}
```

**Comment by tomrav** [comment]
I think this issue may have been resolved in the latest version of `csso` (see [here](https://github.com/css/csso/issues/380)).

Can you try regenerating your dependencies (lock-file) to see if this is resolved?

**Comment by dangreen** [comment]
@tomrav 

Latest `@stylable/optimizer` depends on `csso@3.5.1`: https://unpkg.com/browse/@stylable/optimizer@2.3.1/package.json

`csso@3.5.1` is latest v3 release.

`csso@3.5.1` is installed

**Comment by tomrav** [comment]
You're right, we've updated that major version on the master branch, but have yet to publish that change. I really hope to get it done today.

**Comment by tomrav** [comment]
Publish successful, please try now.
